### ISSUE TITLE
Admin UI buttons not show

### ISSUE THREAD

**Issue by porisjohn** [umputun/remark42#964]
Version 1.7.1,Get from github release page and build by self.

When i set the ADMIN_SHARED_ID to my ID(login via email), the Admin UI button not shown(Just like a normal user) and cannot delete or pin others comment. I press F12 to see the JSON response, It returns me admin: "true" but no button shows.

![1](https://user-images.githubusercontent.com/83451507/116684081-74fbcd80-a9eb-11eb-9e82-6d5be8e4c1d3.png)

my panel is looks like this

![2](https://user-images.githubusercontent.com/83451507/116684087-77f6be00-a9eb-11eb-9c73-cc5ad95982a5.png)

 but i see [Admin-UI](https://github.com/umputun/remark42/wiki/Admin-UI) has many button to manage posts.

the startup env config file here

```
REMARK_URL=https://mysite.com
SECRET=secret
SITE=mysite
AUTH_ANON=true
EMOJI=true
SMTP_HOST=mysite.com
SMTP_PORT=465
SMTP_TLS=true
SMTP_USERNAME=my-blog@mysite.com
SMTP_PASSWORD=password
SMTP_TIMEOUT=600
AUTH_EMAIL_ENABLE=true
AUTH_EMAIL_FROM=my-blog@mysite.com
AUTH_EMAIL_SUBJ=subject
NOTIFY_TYPE=email
NOTIFY_EMAIL_FROM=my-blog@mysite.com
NOTIFY_EMAIL_ADMIN=true
ADMIN_SHARED_EMAIL=my-blog@mysite.com
ADMIN_SHARED_ID=email_227033......4f335d
ADMIN_PASSWD=123456
AUTH_SEND_JWT_HEADER=true
```

**Comment by umputun** [comment]
I can't reproduce the issue. Just created an email admin or remar42 demo site and it worked as expected
![5udnb-202104-30113350-8o4ie](https://user-images.githubusercontent.com/535880/116725772-05b0ba00-a9a8-11eb-8b27-f9ff781044e3.png)

The only reason I have found is a confusing logic with `RESTRICTED_NAMES` preventing admin login via email (should be fixed), but you have not listed this option above.

Have you restarted the remart42/container after you added ADMIN_SHARED_ID?

**Comment by porisjohn** [comment]
My admin name is test with test@mydomain.com, I just try to rebuild remark42 and restart remark42, but not work. 
I run the remark42 with systemd, not the container. It still shows with no Admin UI and JSON returns me admin: "true".
I try to change the username to tester with test@mydomain.com and set the RESTRICTED_NAMES to null(left it with blank) but also not work. If I login via Github, it will shows admin UI but email will not show that.
![1](https://user-images.githubusercontent.com/83451507/116768213-da919d80-aa6f-11eb-94c7-5a842d52a570.jpg)


But I try the other way, If I switch the JWT header on that Admin UI will not show and lost login status in every page refreshing. If I close it, use the Cookie(the remark42 hosting domain are different from my site,so the CORS issues with my site), the Admin UI will show(need force refresh page). Does it means I can't use JWT auth with Admin?

**Comment by umputun** [comment]
> set the RESTRICTED_NAMES to null

you don't need to do it, this is empty by default

>  If I switch the JWT header on that Admin UI 

Not sure what you mean and what "use the Cookie" have to do with this.

Unfortunately, I'm having a hard time parsing your situation. You mention multiple things, like CORS, JWT headers, and so on and I can't follow all of your experiments. The bottom line - auth with email works, admin via email works. I have checked it on the demo site and the only issue I have found was a small conflict with RESTRICTED_NAMES which seems to be completely irrelevant as you not even using this functionality. 

And you don't need to set JWT header mode as this mode intended for some special cases where the client is not a web browser or for some reason can't access cookies.

Another useful piece of information you can obtain - watch logs as you do the login. It may give you some hints of what is wrong/missing in your configuration.

**Comment by porisjohn** [comment]
I try to set the ProxyCORS to true and let it handled by nginx, Then use the newest version of remark42, The issue has been resolved. Not only the RESTRICTED_NAMES issue, But also CORS causes it. Thanks for your patience reply me.
